<h1 style = "color:Brown">Basic Functions to Create NumPy Array</h1>


### 1. numpy.array(): Creates a new ndarray from an object.


### 2. numpy.zeros(): Retuns a new ndarray of specified shape filled with zeros. 


### 3. numpy.ones(): Retuns a new ndarray of specified shape filled with ones. 


### 4. numpy.arange(): Returns a new ndarray with specified range of values.


### 5. numpy.linspace(): Returns a new ndarray with specified number of evenly spaced values in a range.



<h3 style = "color:Blue">Importing Numpy Library</h3>

In [1]:
import numpy as np

<h2 style = "color:Brown">1. numpy.array()</h2>

<h4 style = "color:Blue">array = numpy.array(list)</h4> 

In [5]:
# 1D Array

al1 =  np.array([10, 20, 30])
print(al1)
print(type(al1))

[10 20 30]
<class 'numpy.ndarray'>


In [3]:
# 2D Array

al2 = np.array([[10.5, 20.6, 30.3], [40.6, 50.3, 40.3]])
print(al2)
print(type(al2))

[[10.5 20.6 30.3]
 [40.6 50.3 40.3]]
<class 'numpy.ndarray'>


<h4 style = "color:Blue">array = numpy.array(tuple)</h4> 

In [8]:
at1 = np.array((100, 200, 300))
print(at1)
print(type(at1))

[100 200 300]
<class 'numpy.ndarray'>


<h4 style = "color:Blue">array = numpy.array(range_object)</h4> 

In [10]:
ar1 = np.array(range(0,11,2))
print(ar1)
print(type(ar1))

[ 0  2  4  6  8 10]
<class 'numpy.ndarray'>


<h2 style = "color:Brown">2. numpy.zeros(shape)</h2>

In [2]:
# 1D array

az1 = np.zeros(5)
print(az1)
print(type(az1))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [5]:
# 2D array

az2 = np.zeros((3, 2))
print(az2)
print(type(az2))
print(az2.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>
float64


In [6]:
# 2D array with dtype = int32

az3 = np.zeros((4, 4), dtype = np.int32)
print(az3)
print(az3.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


<h2 style = "color:Brown">3. numpy.ones(shape)</h2>

In [14]:
ao1 = np.ones((3, 4))
print(ao1)
print(type(ao1))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


<h2 style = "color:Brown">3. numpy.arange(start_value, stop_value, step)</h2>

<h4 style = "color:Blue">array = numpy.arange(stop_value)</h4> 

In [9]:
aa1 = np.arange(10)
print(aa1)
print(type(aa1))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


<h4 style = "color:Blue">array = numpy.arange(start_value, stop_value)</h4> 

In [10]:
aa2 = np.arange(2, 11)
print(aa2)

[ 2  3  4  5  6  7  8  9 10]


<h4 style = "color:Blue">array = numpy.arange(start_value, stop_value, step)</h4> 

In [12]:
aa3 = np.arange(1.0, 11.0, 2)
print(aa3)

[1. 3. 5. 7. 9.]


<h2 style = "color:Brown">5. numpy.linspace(start_value, stop_value, number_of_values)</h2>


* Note that default endpoint = True

<h4 style = "color:Blue">array = numpy.linspace(start_value, stop_value)</h4> 


* Default number_of_values is 50

In [20]:
als1 = np.linspace(1, 10)
print(als1)
print(type(als1))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
<class 'numpy.ndarray'>


<h4 style = "color:Blue">array = numpy.linspace(start_value, stop_value, number_of_values)</h4> 

In [27]:
als2 = np.linspace(0, 100, 50, dtype = np.int32)
print(als2)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97 100]


<h2 style = "color:Brown">Reshaping using reshape(shape) method</h2>

In [34]:
arr1 = np.arange(10).reshape((2, 5))
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
